FROM python:3.7.9

COPY . /app
WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["celery", "--app=tasks.app", "worker", "--concurrency=1", "--loglevel=INFO", "--queues=predict", "--without-gossip"]
